### ISSUE TITLE
Loading speed enhancement

### ISSUE THREAD

**Issue by jaxankey** [joommf-attic/oommffield#1]
For big files, looping in python might be an issue. I'm getting the same results by replacing lines 279-288 in oommffield.py with

`field.f = numpy.array(listdata)[1:,0].reshape(n[1],n[0],n[2],3).transpose(1,0,2,3)`

which uses numpy's fast array stuff. Might be moot since the hard drive is probably the bottleneck.

Also line 267 might need to be 

`assert listdata[0][0] == 1234567.0`

(it is for my files).

Cheers, and thanks so much!

**Comment by marijanbeg** [comment]
@fangohr, can you please close this issue?

**Comment by jaxankey** [comment]
Ah! You should totally mention the new project on your github landing page.
:)

**Comment by fangohr** [comment]
Good point - I have just done that (https://github.com/joommf-attic/oommffield/blob/master/README.rst)
